### PR TITLE
Add center text option

### PR DESCRIPTION
**Pull request by git-vince**
This PR adds center text support #24 

Ring
Disc

### CODE REVIEW

**Comment by apgapg** [comment]
Hi thanks for the PR. 
Could you please describe more and attach a screenshot. This will help to understand the scope of this PR better

**Comment by git-vince** [comment]
Updated

**Comment by apgapg** [comment]
Hi sorry for the late response. Can you please rebase and resolve conflicts?
This PR will be a good addition

**Comment by apgapg** [comment]
JgNRalI

**Pull request merged**
