### PR TITLE
Custom legend label

### LINKED ISSUE #63: Show customised labels in legend
When displaying percentage values in the graph, I would like to display the absolute values in the legend.

Would therefore be nice if there is an (optional) formatting function to generate a custom legend text from the data map entry.

(This might also be useful to dynamically abbreviate long legend texts.)

### PR DESCRIPTION
**Pull request by Imagine-Me**
An option for adding custom legend labels. Closes #63 
This PR will add a new property `legendLabels` of type `Map<String,String>` to the widget.
```dart
final legendLabels = <String, String>{
    "Flutter": "Flutter legend",
    "React": "React legend",
    "Xamarin": "Xamarin legend",
    "Ionic": "Ionic legend",
  };


// add to pie chart
legendLabels: legendLabels
```
Screenshot from 2021-11-09 09-29-55

The `key` in property should match with `dataMap`, otherwise fallback to default value.
```dart
final legendLabels = <String, String>{
    "Flutter": "Flutter legend",
    "React": "React legend",
  };


// add to pie chart
legendLabels: legendLabels
```
Screenshot from 2021-11-09 09-46-20

### CODE REVIEW

**Comment by apgapg** [comment]
@Imagine-Me can you please resolve conflicts and re push?

**Comment by Imagine-Me** [comment]
@apgapg Hey, I have resolved the conflicts, can you check once?

**Comment by apgapg** [comment]
@Imagine-Me Thanks a lot for this addition.
For More discussions, visit us on discord: https://discord.gg/PBPETmBZ

**Review by apgapg — APPROVED** [review]
LGTM

**Pull request merged**
