### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by divinepaul**
proposal to update the dataMap.
because it was confusing and and induced errors.

### CODE REVIEW

**Comment by apgapg** [comment]
What issue are you getting? I don't see any plus point in writing .toDouble() as my map is declared as <String,double>, hence it shouldn't create an issue

**Comment by divinepaul** [comment]
Well the documented Map wasn't working well ...
And was throwing errors about the type.

**Comment by divinepaul** [comment]
> What issue are you getting? I don't see any plus point in writing .toDouble() as my map is declared as <String,double>, hence it shouldn't create an issue

......well the .toDouble was the soulution to error that I got while putting a int in to your map in the documentation.

**Comment by apgapg** [comment]
I guess the problem is in the dart version. I remember the new dart accepts 4 instead of 4.0 in padding etc, they said the integers are automatically casted. Could you please check your dart version?

**Comment by divinepaul** [comment]
> 
> 
> I guess the problem is in the dart version. I remember the new dart accepts 4 instead of 4.0 in padding etc, they said the integers are automatically casted. Could you please check your dart version?
```

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (8 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```


its **Dart 2.3.0**

**Pull request closed without merging**
